/rvo_fleet_controller:
  ros__parameters:
    num_robots: 3
    control_rate: 20.0
    max_speed: 0.2
    max_angular_speed: 1.5
    robot_radius: 0.35
    goal_tolerance: 0.25
    
    neighbor_dist: 10.0
    max_neighbors: 10
    time_horizon: 2.0
    time_horizon_obst: 3.0

    # shifted by +2.0, +2.0
    start_positions: [0.8524, 2.8,
                      0.8524, 2.0,
                      0.8524, 1.2]

    obstacle_positions: [1.5, 3.3,
                         2.7, 2.6,
                         1.7, 1.8,
                         2.6, 1.0]

/fleet_goals:
  ros__parameters:
    num_robots: 3
    scenario: "pillar"

    goals_swap:    [3.8288, 2.0, 2.9144, 2.0, 2.0, 2.0]
    goals_straight: [2.0, 3.0, 2.9144, 3.0, 3.8288, 3.0]
    goals_cross:   [3.8288, 3.0, 2.9144, 4.0, 2.0, 3.0]
    goals_home:    [2.0, 2.0, 2.9144, 2.0, 3.8288, 2.0]

    # pillar scenario, shifted
    goals_pillar: [3.6, 1.2,
                   3.6, 2.8,
                   3.6, 2.0]